/**
 * Shared Tailwind theme extension — maps `--tui-*` CSS variables to utility classes.
 * Used by the package preset and the local playground.
 *
 * @type {import("tailwindcss").Config["theme"]}
 */
const tuiColor = (name) => `rgb(var(--tui-${name}) / <alpha-value>)`;

/** @type {import("tailwindcss").Config["theme"]["extend"]} */
const tuiThemeExtend = {
	colors: {
		tui: {
			fg: tuiColor("fg"),
			"fg-muted": tuiColor("fg-muted"),
			border: tuiColor("border"),
			"border-strong": tuiColor("border-strong"),
			surface: tuiColor("surface"),
			"surface-hover": tuiColor("surface-hover"),
			"surface-active": tuiColor("surface-active"),
			ring: tuiColor("ring"),
			ripple: tuiColor("ripple"),
			"progress-default": tuiColor("progress-default"),

			default: tuiColor("default"),
			"default-fg": tuiColor("default-fg"),
			"default-hover": tuiColor("default-hover"),
			"default-active": tuiColor("default-active"),
			"default-soft": tuiColor("default-soft"),
			"default-soft-fg": tuiColor("default-soft-fg"),
			"default-soft-hover": tuiColor("default-soft-hover"),
			"default-soft-active": tuiColor("default-soft-active"),
			"default-gradient-from": tuiColor("default-gradient-from"),
			"default-gradient-to": tuiColor("default-gradient-to"),
			"default-gradient-from-hover": tuiColor("default-gradient-from-hover"),
			"default-gradient-to-hover": tuiColor("default-gradient-to-hover"),
			"default-gradient-from-active": tuiColor("default-gradient-from-active"),
			"default-gradient-to-active": tuiColor("default-gradient-to-active"),
			"default-spatial-from": tuiColor("default-spatial-from"),
			"default-spatial-to": tuiColor("default-spatial-to"),
			"default-spatial-fg": tuiColor("default-spatial-fg"),

			primary: tuiColor("primary"),
			"primary-fg": tuiColor("primary-fg"),
			"primary-hover": tuiColor("primary-hover"),
			"primary-active": tuiColor("primary-active"),
			"primary-soft": tuiColor("primary-soft"),
			"primary-soft-fg": tuiColor("primary-soft-fg"),
			"primary-soft-hover": tuiColor("primary-soft-hover"),
			"primary-soft-active": tuiColor("primary-soft-active"),
			"primary-subtle": tuiColor("primary-subtle"),
			"primary-muted": tuiColor("primary-muted"),
			"primary-gradient-from": tuiColor("primary-gradient-from"),
			"primary-gradient-to": tuiColor("primary-gradient-to"),
			"primary-gradient-from-hover": tuiColor("primary-gradient-from-hover"),
			"primary-gradient-to-hover": tuiColor("primary-gradient-to-hover"),
			"primary-gradient-from-active": tuiColor("primary-gradient-from-active"),
			"primary-gradient-to-active": tuiColor("primary-gradient-to-active"),
			"primary-spatial-from": tuiColor("primary-spatial-from"),
			"primary-spatial-to": tuiColor("primary-spatial-to"),

			secondary: tuiColor("secondary"),
			"secondary-fg": tuiColor("secondary-fg"),
			"secondary-hover": tuiColor("secondary-hover"),
			"secondary-active": tuiColor("secondary-active"),
			"secondary-soft": tuiColor("secondary-soft"),
			"secondary-soft-fg": tuiColor("secondary-soft-fg"),
			"secondary-soft-hover": tuiColor("secondary-soft-hover"),
			"secondary-soft-active": tuiColor("secondary-soft-active"),
			"secondary-subtle": tuiColor("secondary-subtle"),
			"secondary-muted": tuiColor("secondary-muted"),
			"secondary-gradient-from": tuiColor("secondary-gradient-from"),
			"secondary-gradient-to": tuiColor("secondary-gradient-to"),
			"secondary-gradient-from-hover": tuiColor("secondary-gradient-from-hover"),
			"secondary-gradient-to-hover": tuiColor("secondary-gradient-to-hover"),
			"secondary-gradient-from-active": tuiColor("secondary-gradient-from-active"),
			"secondary-gradient-to-active": tuiColor("secondary-gradient-to-active"),
			"secondary-spatial-from": tuiColor("secondary-spatial-from"),
			"secondary-spatial-to": tuiColor("secondary-spatial-to"),

			success: tuiColor("success"),
			"success-fg": tuiColor("success-fg"),
			"success-hover": tuiColor("success-hover"),
			"success-active": tuiColor("success-active"),
			"success-soft": tuiColor("success-soft"),
			"success-soft-fg": tuiColor("success-soft-fg"),
			"success-soft-hover": tuiColor("success-soft-hover"),
			"success-soft-active": tuiColor("success-soft-active"),
			"success-subtle": tuiColor("success-subtle"),
			"success-muted": tuiColor("success-muted"),
			"success-gradient-from": tuiColor("success-gradient-from"),
			"success-gradient-to": tuiColor("success-gradient-to"),
			"success-gradient-from-hover": tuiColor("success-gradient-from-hover"),
			"success-gradient-to-hover": tuiColor("success-gradient-to-hover"),
			"success-gradient-from-active": tuiColor("success-gradient-from-active"),
			"success-gradient-to-active": tuiColor("success-gradient-to-active"),
			"success-spatial-from": tuiColor("success-spatial-from"),
			"success-spatial-to": tuiColor("success-spatial-to"),

			warning: tuiColor("warning"),
			"warning-fg": tuiColor("warning-fg"),
			"warning-hover": tuiColor("warning-hover"),
			"warning-active": tuiColor("warning-active"),
			"warning-soft": tuiColor("warning-soft"),
			"warning-soft-fg": tuiColor("warning-soft-fg"),
			"warning-soft-hover": tuiColor("warning-soft-hover"),
			"warning-soft-active": tuiColor("warning-soft-active"),
			"warning-subtle": tuiColor("warning-subtle"),
			"warning-muted": tuiColor("warning-muted"),
			"warning-gradient-from": tuiColor("warning-gradient-from"),
			"warning-gradient-to": tuiColor("warning-gradient-to"),
			"warning-gradient-from-hover": tuiColor("warning-gradient-from-hover"),
			"warning-gradient-to-hover": tuiColor("warning-gradient-to-hover"),
			"warning-gradient-from-active": tuiColor("warning-gradient-from-active"),
			"warning-gradient-to-active": tuiColor("warning-gradient-to-active"),
			"warning-spatial-from": tuiColor("warning-spatial-from"),
			"warning-spatial-to": tuiColor("warning-spatial-to"),

			danger: tuiColor("danger"),
			"danger-fg": tuiColor("danger-fg"),
			"danger-hover": tuiColor("danger-hover"),
			"danger-active": tuiColor("danger-active"),
			"danger-soft": tuiColor("danger-soft"),
			"danger-soft-fg": tuiColor("danger-soft-fg"),
			"danger-soft-hover": tuiColor("danger-soft-hover"),
			"danger-soft-active": tuiColor("danger-soft-active"),
			"danger-subtle": tuiColor("danger-subtle"),
			"danger-muted": tuiColor("danger-muted"),
			"danger-gradient-from": tuiColor("danger-gradient-from"),
			"danger-gradient-to": tuiColor("danger-gradient-to"),
			"danger-gradient-from-hover": tuiColor("danger-gradient-from-hover"),
			"danger-gradient-to-hover": tuiColor("danger-gradient-to-hover"),
			"danger-gradient-from-active": tuiColor("danger-gradient-from-active"),
			"danger-gradient-to-active": tuiColor("danger-gradient-to-active"),
			"danger-spatial-from": tuiColor("danger-spatial-from"),
			"danger-spatial-to": tuiColor("danger-spatial-to"),
		},
	},
};

module.exports = { tuiThemeExtend };
